const SAVEKEY='chufa-tutorial-v03';
const WORLDKEY='chinese-word-tactics-world-v1';
let stageIndex=0,state=null,history=[],selected=false,inspect=false,completed=new Set(),screen='tutorial';
let stageSession={mode:'first-play',returnTo:'journey'},completionTimer=null;
let worldState={visited:[],completedMilestones:[]};
const $=s=>document.querySelector(s),gridEl=$('#grid'),statusEl=$('#status');
const key=p=>p[0]+','+p[1],dist=(a,b)=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]);
function locate(g,ch){for(let r=0;r<g.length;r++)for(let c=0;c<g[r].length;c++)if(g[r][c]===ch)return[r,c]}
function initialState(st){return{hero:locate(st.grid,'S'),phase:st.wolf?.initial||0,stone:false,crossed:false,entry:null,entered:false,inspected:false,exited:false,turn:0}}
const clone=v=>JSON.parse(JSON.stringify(v)),current=()=>STAGES[stageIndex];
function wolfPos(st=current(),s=state,phase=s.phase){return st.wolf?st.wolf.cycle[phase]:null}
function nextPhase(st=current(),s=state){return st.wolf?(s.phase+1)%st.wolf.cycle.length:s.phase}
const tileAt=pos=>current().grid[pos[0]]?.[pos[1]],stonePos=()=>locate(current().grid,'K'),atExit=()=>tileAt(state.hero)==='E';
const inList=(value,list)=>Array.isArray(list)&&list.includes(value);
function isWin(){const w=current().win;return(!w.includes('stone')||state.stone)&&(!w.includes('crossed')||state.crossed)&&(!w.includes('at_exit')||atExit())&&(!w.includes('entered')||state.entered)&&(!w.includes('inspected')||state.inspected)&&(!w.includes('exited')||state.exited)}
function milestoneProgress(){const values=window.GameFlow?.progress?.()?.completedMilestones;return Array.isArray(values)?values:worldState.completedMilestones}
function heroName(){return window.JourneyProgress?.getHeroRole(milestoneProgress())==='hero'?'용사':'소년'}
function setStatus(msg,type=''){statusEl.textContent=(heroName()==='소년'?msg.replaceAll('용사를','소년을').replaceAll('용사가','소년이').replaceAll('용사는','소년은').replaceAll('용사','소년'):msg);statusEl.className='status'+(type?' '+type:'')}
function save(){try{if(stageSession.mode!=='replay')localStorage.setItem(SAVEKEY,JSON.stringify({stageIndex,state,history,selected,inspect,completed:[...completed]}));localStorage.setItem(WORLDKEY,JSON.stringify(worldState))}catch{setStatus('진행 상태를 저장하지 못했어. 이 탭에서는 계속 플레이할 수 있어.','bad')}}
function load(){
  const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
  const x=read(SAVEKEY),w=read(WORLDKEY),ids=v=>Array.isArray(v)?v.filter(id=>typeof id==='string'):[];
  if(w)worldState={visited:ids(w.visited),completedMilestones:ids(w.completedMilestones)};
  if(x)completed=new Set(ids(x.completed).filter(id=>STAGES.some(st=>st.id===id)));
  const st=STAGES[x?.stageIndex],s=x?.state;
  const valid=v=>v&&Array.isArray(v.hero)&&v.hero.length===2&&v.hero.every(Number.isInteger)&&st?.grid[v.hero[0]]?.[v.hero[1]]&&Number.isInteger(v.phase)&&v.phase>=0&&(!st.wolf||v.phase<st.wolf.cycle.length)&&Number.isInteger(v.turn)&&v.turn>=0;
  if(!st||!valid(s))return false;
  stageIndex=x.stageIndex;state=s;history=Array.isArray(x.history)?x.history.filter(valid):[];selected=!!x.selected;inspect=!!x.inspect;return true;
}
function acceptedMove(pos){const st=current(),ch=tileAt(pos);if(!ch||dist(state.hero,pos)!==1||ch==='#'||ch==='K'||ch==='L'||ch==='X'||(ch==='G'&&!state.stone))return false;if(st.wolf){const cur=wolfPos(st,state),n=st.wolf.cycle[nextPhase(st,state)];if(dist(pos,cur)<=st.wolf.radius||dist(pos,n)<=st.wolf.radius)return false}return true}
function arrowFor(pos){const dr=pos[0]-state.hero[0],dc=pos[1]-state.hero[1];return dr===-1?'↑':dr===1?'↓':dc===-1?'←':'→'}
function resetStage(quiet=false){clearTimeout(completionTimer);closeSheet();screen='tutorial';showTutorial();state=initialState(current());history=[];selected=current().id!=='stage-0';inspect=false;if(!quiet)setStatus(current().id==='stage-0'?'용사를 누르고, 화살표가 보이는 옆 칸을 눌러봐.':current().wolf?'늑대는 행동할 때마다 움직여. 1턴 기다리기는 제자리에 머물며 늑대의 순찰만 진행시켜.':'목표와 지형을 보고 네 길을 찾아봐.','info');save();render()}
function markGoal(text,word,done){return text.replace(word,`<span class="${done?'done':'hot'}">${word}</span>`)}
function renderGoal(){let st=current(),g=st.goal;if(st.id==='stage-1'&&state.stone)g=st.goalAfter;if(st.win.includes('stone'))g=markGoal(g,'接近',state.stone);if(st.win.includes('crossed'))g=markGoal(g,'通過',state.crossed);if(st.win.includes('entered'))g=markGoal(g,'進入',state.entered);if(st.win.includes('inspected'))g=g.replace('看路標',`<span class="${state.inspected?'done':'hot'}">看路標</span>`);if(st.win.includes('exited'))g=markGoal(g,'退出',state.exited);$('#goal').innerHTML=g;$('#ruleLine').textContent=st.rule||''}
function descTile(ch,pos){if(key(pos)===key(state.hero))return heroName()+(heroName()==='소년'?'이':'가')+' 있는 칸';if(current().wolf&&key(pos)===key(wolfPos()))return'늑대';return{'#':'수풀, 지나갈 수 없음','.':'길','S':'길','E':'출구','K':'낡은 비석','G':state.stone?'열린 문':'닫힌 문','R':'유적 통로','X':'가시, 위험한 바닥','W':'길','I':'관문 안쪽','D':'열린 관문','L':'오래된 길표지'}[ch]||'길'}
function render(){const st=current();$('#stageKicker').textContent=st.kicker||`튜토리얼 ${stageIndex}/5`;$('#stageTitle').textContent=st.subtitle;renderGoal();const rows=st.grid.length,cols=st.grid[0].length;gridEl.style.gridTemplateColumns=`repeat(${cols},var(--cell))`;gridEl.innerHTML='';for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const ch=st.grid[r][c],b=document.createElement('button'),pos=[r,c];b.className='cell '+(ch==='#'?'wall':ch==='E'?'exit':ch==='K'?'stone':ch==='G'?'gate':ch==='R'?'ruin':ch==='X'?'hazard':ch==='I'?'interior':ch==='D'?'checkpoint':ch==='L'?'sign':'floor');if(ch==='K'&&state.stone)b.classList.add('active');if(ch==='G'&&state.stone)b.classList.add('open');if(ch==='R'&&state.crossed)b.classList.add('crossed');if(ch==='L'&&state.inspected)b.classList.add('active');if(selected&&!inspect&&acceptedMove(pos)){b.classList.add('moveable');const a=document.createElement('span');a.className='move-arrow';a.textContent=arrowFor(pos);a.setAttribute('aria-hidden','true');b.appendChild(a)}if(inspect)b.classList.add('inspectable');b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${String.fromCharCode(65+c)}${r+1}, ${descTile(ch,pos)}`);b.addEventListener('click',()=>tapCell(pos));if(key(pos)===key(state.hero)){const x=document.createElement('span');x.className='hero';x.textContent='🧑‍🎒';x.setAttribute('aria-hidden','true');b.appendChild(x)}if(st.wolf&&key(pos)===key(wolfPos())){const x=document.createElement('span');x.className='wolf';x.textContent='🐺';x.setAttribute('aria-hidden','true');b.appendChild(x)}gridEl.appendChild(b)}$('#words').innerHTML='';st.words.forEach(w=>{const b=document.createElement('button');b.className='wordbtn';if((w==='接近'&&state.stone)||(w==='通過'&&state.crossed)||(w==='到達'&&atExit())||(w==='進入'&&state.entered)||(w==='退出'&&state.exited))b.classList.add('done');b.textContent=w;b.onclick=()=>showWord(w);$('#words').appendChild(b)});const wait=$('#waitBtn'),controls=$('.controls'),hasWait=!!st.wolf;wait.hidden=!hasWait;wait.disabled=!hasWait;controls.style.gridTemplateColumns=hasWait?'1.25fr 1fr 1fr':'1fr 1fr';$('#inspectBtn').textContent=inspect?'이동으로':'살펴보기';$('#inspectBtn').className='control'+(inspect?' mode':'');$('#undoBtn').disabled=!history.length}
function tapCell(pos){if(inspect){showInspect(pos);return}if(!selected){if(key(pos)===key(state.hero)){selected=true;setStatus('좋아. 이제 옆 칸을 눌러 이동해.','info');render();return}setStatus('먼저 용사를 눌러줘.','info');return}if(key(pos)===key(state.hero)){setStatus('이동할 옆 칸을 골라봐.');return}if(dist(state.hero,pos)!==1){setStatus('한 번에 상하좌우 한 칸만 움직일 수 있어.','info');return}attemptMove(pos,false)}
function attemptMove(pos,isWait){if(screen!=='tutorial'||isWin())return;const st=current(),ch=tileAt(pos);if(!isWait){if(!ch||ch==='#'||ch==='K'||ch==='L'||(ch==='G'&&!state.stone)){setStatus(ch==='G'?'문이 아직 닫혀 있어.':'그쪽으로는 갈 수 없어.','info');return}if(ch==='X'){window.flashHeroReaction?.('panic');setStatus('這裡有危險。 가시를 피해 다른 길을 찾아봐.','bad');return}}const np=isWait?state.hero:pos;if(st.wolf){const cur=wolfPos(st,state),np2=st.wolf.cycle[nextPhase(st,state)];if(dist(np,cur)<=st.wolf.radius||dist(np,np2)<=st.wolf.radius){window.flashHeroReaction?.('panic');setStatus('太接近野狼了。 늑대와 거리를 더 두어야 해.','bad');return}}history.push(clone(state));const oldHero=clone(state.hero),oldTile=tileAt(oldHero);state.hero=clone(np);if(st.wolf)state.phase=nextPhase(st,state);state.turn++;let messageSet=false;const k=stonePos();if(k&&!state.stone&&dist(state.hero,k)===1){state.stone=true;setStatus('接近石碑 — 비석이 빛나며 길이 열렸어.','good');messageSet=true}if(st.ruin&&!isWait){const newTile=tileAt(state.hero),portals=st.ruin.portals;if(newTile==='R'&&oldTile!=='R'){const idx=portals.findIndex(p=>key(p)===key(oldHero));state.entry=idx>=0?idx:null}if(oldTile==='R'&&newTile!=='R'){const out=portals.findIndex(p=>key(p)===key(state.hero));if(state.entry!==null&&out>=0&&out!==state.entry){state.crossed=true;setStatus('已通過遺跡。 유적을 반대편까지 지나왔어.','good');messageSet=true}state.entry=null}}if(st.enterExit&&!isWait){const newTile=tileAt(state.hero),cfg=st.enterExit;if(!state.entered&&oldTile===cfg.boundary&&inList(newTile,cfg.insideChars)){state.entered=true;setStatus('已進入關口。 관문 안쪽으로 들어왔어.','good');messageSet=true}if(oldTile===cfg.boundary&&inList(newTile,cfg.outsideChars)&&state.entered){if(state.inspected){state.exited=true;setStatus('已退出關口。 확인을 마치고 다시 밖으로 나왔어.','good');messageSet=true}else{setStatus('路標還沒看。 먼저 안쪽 길표지를 확인해봐.','info');messageSet=true}}}if(atExit()&&!isWin()){if(st.win.includes('crossed')&&!state.crossed){setStatus('還沒通過遺跡。 출구에는 왔지만 유적을 아직 통과하지 않았어.','info');messageSet=true}else if(st.win.includes('stone')&&!state.stone){setStatus('아직 비석에 접근하지 않았어.','info');messageSet=true}}if(isWin()){if(stageSession.mode!=='replay')completed.add(st.id);window.GameFlow?.recordStageComplete(st.id,stageSession);save();render();clearTimeout(completionTimer);completionTimer=setTimeout(()=>{if(screen==='tutorial'&&current().id===st.id&&isWin())showComplete()},120);return}save();render();if(isWait)setStatus('한 턴 기다렸어. 늑대의 위치가 바뀌었어.','info');else if(!messageSet)setStatus('한 칸 이동했어.')}
function showWord(w){const x=WORDS[w];openSheet(`<h2>${w}</h2><div class="pinyin">${x.p}</div><div class="meaning">${x.k}</div><div class="example">${x.ex}</div><div class="gamerule"><strong>이 판에서는</strong><br>${x.rule}</div><div class="sheetactions"><button onclick="closeSheet()">닫기</button></div>`)}
function showInspect(pos){const st=current(),ch=tileAt(pos),title=descTile(ch,pos);let extra='';if(ch==='L'&&st.enterExit){if(dist(state.hero,pos)!==1){setStatus('길표지는 가까이 가야 글자를 확인할 수 있어.','info');return}if(!state.inspected){history.push(clone(state));state.inspected=true;save();render();setStatus('已看過路標。 흐리던 글자가 잠깐 또렷해졌어.','good')}extra='<div class="gamerule"><strong>北門</strong><br>오래된 글씨가 희미하다. 가까이 서자 두 글자가 잠깐 또렷하게 보였다.</div>'}if(st.wolf&&key(pos)===key(wolfPos())){const cur=wolfPos(),n=st.wolf.cycle[nextPhase()];extra=`<div class="gamerule">위험 범위: 현재와 다음 위치의 상하좌우 한 칸.<br>다음 행동: ${key(cur)===key(n)?'여기서 기다림':`${String.fromCharCode(65+n[1])}${n[0]+1}로 이동`}.</div>`}if(ch==='R'&&st.ruin)extra+='<div class="gamerule">연결된 유적 통로야. 한쪽 입구에서 들어가 다른 입구로 나오면 <b>通過</b>가 성립해.</div>';if(ch==='K')extra+='<div class="gamerule">위에 올라갈 수는 없어. 가까이 가면 반응할 것 같아.</div>';if(ch==='X')extra+='<div class="gamerule">위험한 가시야. 이 칸으로 들어가는 행동은 확정되지 않아.</div>';openSheet(`<h2>${title}</h2><div class="pinyin">${String.fromCharCode(65+pos[1])}${pos[0]+1}</div>${extra}<div class="sheetactions"><button onclick="closeSheet()">닫기</button></div>`)}
function openSheet(html){$('#sheet').innerHTML=html;$('#scrim').classList.add('open')}
window.closeSheet=()=>$('#scrim').classList.remove('open');
function showComplete(){if(window.GameFlow){GameFlow.showStageComplete(current().id,{...stageSession});return;}const st=current(),last=stageIndex===STAGES.length-1;openSheet(`<div class="completeMark">${last?'🌄':'✓'}</div><h2 style="text-align:center">${last?'튜토리얼 완료':'스테이지 완료'}</h2><div class="story">${st.story}</div><div class="sheetactions">${stageIndex>0?'<button class="secondary" onclick="replayStage()">다시 해보기</button>':''}<button onclick="nextStage()">${last?'월드맵으로':'다음 스테이지'}</button></div>`)}
window.nextStage=()=>{closeSheet();if(stageIndex<STAGES.length-1){stageIndex++;resetStage()}else enterWorld()};
window.replayStage=()=>{closeSheet();resetStage()};window.jumpStage=i=>{stageIndex=i;closeSheet();resetStage()};
function showMenu(){if(window.GameFlow){GameFlow.showMenu();return;}const list=STAGES.map((s,i)=>`<button class="stagepick" onclick="jumpStage(${i})"><strong>${completed.has(s.id)?'✓ ':''}${i}. ${s.subtitle}</strong><small>${s.title}</small></button>`).join('');const worldButton=completed.has('stage-5')?'<button class="stagepick" onclick="closeSheet();enterWorld()"><strong>🗺️ 월드맵</strong><small>튜토리얼 이후의 세계로 이동</small></button>':'';openSheet(`<h2>出發</h2><div class="pinyin">튜토리얼 스테이지 선택</div><div class="menuList">${list}${worldButton}</div><div class="sheetactions"><button class="secondary" onclick="closeSheet()">닫기</button></div>`)}
function showView(view){clearTimeout(completionTimer);closeSheet();screen=view;document.querySelectorAll('.appView').forEach(el=>{el.hidden=el.id!==(view==='tutorial'?'tutorialView':view+'View')})}
function showTutorial(){showView('tutorial')}
function isRegionLocked(region){return region.status==='locked'&&!milestoneProgress().includes(region.requires)}
function enterWorld(){showView('world');renderWorld()}
function renderWorld(){const list=$('#worldRegions');list.innerHTML='';WORLD.regions.forEach(region=>{const locked=isRegionLocked(region),visited=worldState.visited.includes(region.id),b=document.createElement('button');b.className='regionCard '+(locked?'locked':region.status==='recommended'?'recommended':'available');b.disabled=locked;b.innerHTML=`<span class="regionState">${locked?'🔒 잠김':region.status==='recommended'?'◇ 권장 경로 있음':'● 이동 가능'}</span><strong>${visited?'✓ ':''}${region.name}</strong><small>${region.subtitle}</small><span class="regionNote">${region.note}</span>`;b.onclick=()=>openRegion(region);list.appendChild(b)});$('#worldHint').textContent='세 마을은 자유롭게 선택할 수 있어. ◇ 표시는 추천일 뿐, 들어가는 데 제한은 없어.'}
function openRegion(region){if(!worldState.visited.includes(region.id))worldState.visited.push(region.id);save();renderWorld();if(window.GameFlow?.enterRegion?.(region.id))return;openSheet(`<h2>${region.name}</h2><div class="pinyin">${region.subtitle}</div><div class="meaning">${region.note}</div><div class="gamerule"><strong>첫 목표어</strong><br>${region.targets.join(' · ')}</div><div class="tiny">이 지역의 의뢰는 준비 중이야. 방문과 핵심 의뢰 완료는 별도로 기록해.</div><div class="sheetactions"><button onclick="closeSheet()">확인</button></div>`)}
window.returnToTutorial=()=>{showTutorial();render()};
$('#scrim').addEventListener('click',e=>{if(e.target.id==='scrim')closeSheet()});$('#menuBtn').onclick=showMenu;$('#resetBtn').onclick=()=>resetStage();$('#inspectBtn').onclick=()=>{inspect=!inspect;setStatus(inspect?'살펴보기 모드야. 지형이나 늑대를 눌러봐.':'이동 모드로 돌아왔어.','info');render()};$('#undoBtn').onclick=()=>{if(!history.length)return;clearTimeout(completionTimer);state=history.pop();setStatus('직전 행동 전으로 되돌렸어.','info');save();render()};$('#waitBtn').onclick=()=>attemptMove(state.hero,true);$('#worldBackBtn').onclick=()=>returnToTutorial();
const hasSavedGame=load();
if(!hasSavedGame)resetStage(true);showTutorial();render();if(current().id==='stage-0'&&!selected)setStatus('용사를 누르고, 화살표가 보이는 옆 칸을 눌러봐.','info');else if(current().wolf)setStatus('늑대는 행동할 때마다 움직여. 1턴 기다리기는 제자리에 머물며 늑대의 순찰만 진행시켜.','info');else setStatus('목표와 지형을 보고 네 길을 찾아봐.','info');

// Small public adapter: story/journey code never touches tactical globals directly.
window.TacticalGame=Object.freeze({
  hasSavedGame,
  stageId:()=>current().id,
  showView,showWorld:enterWorld,openSheet,closeSheet:()=>closeSheet(),showWord,
  playStage(id,options={}){
    const index=STAGES.findIndex(stage=>stage.id===id);
    if(index<0)return false;
    stageSession={...options,mode:options.mode==='replay'?'replay':'first-play'};
    stageIndex=index;resetStage();return true;
  },
  resumeStage(id,options={}){
    // Replay uses scratch state. Restore the untouched campaign save on return.
    if(!load()||current().id!==id)return false;
    stageSession={...options,mode:'first-play'};
    showTutorial();render();
    setStatus('목표와 지형을 보고 네 길을 찾아봐.','info');
    return true;
  }
});
