const WORDS={
'接近':{p:'ㄐㄧㄝ ㄐㄧㄣˋ',k:'가까이 가다, 접근하다',ex:'我慢慢接近石碑。',rule:'이 게임에서는 석비와 상하좌우 한 칸 거리까지 가면 석비가 반응해.'},
'遠離':{p:'ㄩㄢˇ ㄌㄧˊ',k:'멀어지다, 멀리 떨어지다',ex:'請遠離危險的地方。',rule:'늑대의 위험 범위와 거리를 두어야 해. 매번 거리가 늘어나야 한다는 뜻은 아니야.'},
'通過':{p:'ㄊㄨㄥ ㄍㄨㄛˋ',k:'통과하다, 지나가다',ex:'我們要通過這個遺跡。',rule:'유적의 한쪽 입구로 들어가 다른 쪽 입구로 나와야 통과한 것으로 판정해.'},
'到達':{p:'ㄉㄠˋ ㄉㄚˊ',k:'도착하다, 이르다',ex:'最後到達出口。',rule:'필요한 조건을 마친 뒤 출구에 도착하면 스테이지가 끝나.'},
'避開':{p:'ㄅㄧˋ ㄎㄞ',k:'피하다, 비켜 가다',ex:'避開危險，繼續前進。',rule:'가시 칸으로 들어가는 행동은 확정되지 않아. 다른 경로를 찾아야 해.'}
};
const STAGES=[
{id:'stage-0',title:'出發',subtitle:'마을을 떠나다',grid:['.E.','...','...','.S.'],goal:'到村口去。',words:[],win:['at_exit'],story:'소년은 뒤를 돌아보았다.\n익숙한 마을은 이제 조금씩 멀어지고 있었다.'},
{id:'stage-1',title:'接近',subtitle:'낡은 석비',grid:['##E##','#...#','##G##','#...#','#K..#','#...#','##S##'],goal:'接近石碑。',goalAfter:'走到出口。',words:['接近'],win:['stone','at_exit'],story:'「방금… 글자가 빛난 건가?」'},
{id:'stage-2',title:'遠離',subtitle:'늑대가 있는 길',grid:['##E##','.....','.#.#.','...W.','.#.#.','.....','##S##'],goal:'遠離野狼，走到出口。',words:['遠離'],win:['at_exit'],wolf:{cycle:[[3,3]],radius:1},story:'가장 짧은 길이 언제나 좋은 길은 아니었다.'},
{id:'stage-3',title:'通過・到達',subtitle:'폐허를 지나서',grid:['#..E#','#.#.#','#R#.#','#R#.#','#R#.#','#.#.#','#..S#'],goal:'通過遺跡，然後到達出口。',words:['通過','到達'],win:['crossed','at_exit'],ruin:{portals:[[1,1],[5,1]]},story:'지나가는 것과 도착하는 것.\n비슷해 보여도 길 위에서는 전혀 다른 일이었다.'},
{id:'stage-4',title:'避開',subtitle:'위험한 길',grid:['##E##','.....','.X.X.','..X..','.X.X.','.....','##S##'],goal:'避開危險，到達出口。',words:['避開','到達'],win:['at_exit'],story:'목적지만큼, 그곳까지 가는 길도 중요했다.'},
{id:'stage-5',title:'走出森林',subtitle:'숲을 빠져나가라',grid:['....E','.#.#.','.#..W','.##X.','.RRR.','.K##.','S....'],goal:'接近石碑，通過遺跡，到達出口。',rule:'遠離野狼，避開危險。',words:['接近','遠離','通過','到達','避開'],win:['stone','crossed','at_exit'],ruin:{portals:[[4,0],[4,4]]},wolf:{initial:3,cycle:[[2,2],[2,2],[2,3],[2,4],[2,4],[2,3]],radius:1},story:'少年離開了熟悉的村子。\n他第一次發現，這個世界的「話」似乎有一種奇怪的力量。\n\n「救命！」'}
];
const SAVEKEY='chufa-tutorial-v03';
let stageIndex=0,state=null,history=[],selected=false,inspect=false,completed=new Set();
const $=s=>document.querySelector(s),gridEl=$('#grid'),statusEl=$('#status');
const key=p=>p[0]+','+p[1],dist=(a,b)=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]);
function locate(g,ch){for(let r=0;r<g.length;r++)for(let c=0;c<g[r].length;c++)if(g[r][c]===ch)return[r,c]}
function initialState(st){return{hero:locate(st.grid,'S'),phase:st.wolf?.initial||0,stone:false,crossed:false,entry:null,turn:0}}
const clone=v=>JSON.parse(JSON.stringify(v)),current=()=>STAGES[stageIndex];
function wolfPos(st=current(),s=state,phase=s.phase){return st.wolf?st.wolf.cycle[phase]:null}
function nextPhase(st=current(),s=state){return st.wolf?(s.phase+1)%st.wolf.cycle.length:s.phase}
const tileAt=pos=>current().grid[pos[0]]?.[pos[1]],stonePos=()=>locate(current().grid,'K'),atExit=()=>tileAt(state.hero)==='E';
function isWin(){const w=current().win;return(!w.includes('stone')||state.stone)&&(!w.includes('crossed')||state.crossed)&&(!w.includes('at_exit')||atExit())}
function setStatus(msg,type=''){statusEl.textContent=msg;statusEl.className='status'+(type?' '+type:'')}
function save(){try{localStorage.setItem(SAVEKEY,JSON.stringify({stageIndex,state,history,selected,inspect,completed:[...completed]}))}catch{setStatus('진행 상태를 저장하지 못했어. 이 탭에서는 계속 플레이할 수 있어.','bad')}}
function load(){try{const x=JSON.parse(localStorage.getItem(SAVEKEY)||'null');if(!x||!STAGES[x.stageIndex]||!x.state)return false;stageIndex=x.stageIndex;state=x.state;history=x.history||[];selected=!!x.selected;inspect=!!x.inspect;completed=new Set(x.completed||[]);return true}catch{return false}}
function acceptedMove(pos){const st=current(),ch=tileAt(pos);if(!ch||dist(state.hero,pos)!==1||ch==='#'||ch==='K'||ch==='X'||(ch==='G'&&!state.stone))return false;if(st.wolf){const cur=wolfPos(st,state),n=st.wolf.cycle[nextPhase(st,state)];if(dist(pos,cur)<=st.wolf.radius||dist(pos,n)<=st.wolf.radius)return false}return true}
function arrowFor(pos){const dr=pos[0]-state.hero[0],dc=pos[1]-state.hero[1];return dr===-1?'↑':dr===1?'↓':dc===-1?'←':'→'}
function resetStage(quiet=false){state=initialState(current());history=[];selected=stageIndex>0;inspect=false;if(!quiet)setStatus(stageIndex===0?'용사를 누르고, 화살표가 보이는 옆 칸을 눌러봐.':stageIndex===5?'늑대는 행동할 때마다 움직여. 1턴 기다리기는 제자리에 머물며 늑대의 순찰만 진행시켜.':'목표와 지형을 보고 네 길을 찾아봐.','info');save();render()}
function markGoal(text,word,done){return text.replace(word,`<span class="${done?'done':'hot'}">${word}</span>`)}
function renderGoal(){let st=current(),g=st.goal;if(stageIndex===1&&state.stone)g=st.goalAfter;if(st.win.includes('stone'))g=markGoal(g,'接近',state.stone);if(st.win.includes('crossed'))g=markGoal(g,'通過',state.crossed);$('#goal').innerHTML=g;$('#ruleLine').textContent=st.rule||''}
function descTile(ch,pos){if(key(pos)===key(state.hero))return'용사가 있는 칸';if(current().wolf&&key(pos)===key(wolfPos()))return'늑대';return{'#':'수풀, 지나갈 수 없음','.':'길','S':'길','E':'출구','K':'낡은 석비','G':state.stone?'열린 문':'닫힌 문','R':'유적 통로','X':'가시, 위험한 바닥','W':'길'}[ch]||'길'}
function render(){const st=current();$('#stageKicker').textContent=`튜토리얼 ${stageIndex}/5`;$('#stageTitle').textContent=`${st.title} · ${st.subtitle}`;renderGoal();const rows=st.grid.length,cols=st.grid[0].length;gridEl.style.gridTemplateColumns=`repeat(${cols},var(--cell))`;gridEl.innerHTML='';for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const ch=st.grid[r][c],b=document.createElement('button'),pos=[r,c];b.className='cell '+(ch==='#'?'wall':ch==='E'?'exit':ch==='K'?'stone':ch==='G'?'gate':ch==='R'?'ruin':ch==='X'?'hazard':'floor');if(ch==='K'&&state.stone)b.classList.add('active');if(ch==='G'&&state.stone)b.classList.add('open');if(ch==='R'&&state.crossed)b.classList.add('crossed');if(selected&&!inspect&&acceptedMove(pos)){b.classList.add('moveable');const a=document.createElement('span');a.className='move-arrow';a.textContent=arrowFor(pos);a.setAttribute('aria-hidden','true');b.appendChild(a)}if(inspect)b.classList.add('inspectable');b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${String.fromCharCode(65+c)}${r+1}, ${descTile(ch,pos)}`);b.addEventListener('click',()=>tapCell(pos));if(key(pos)===key(state.hero)){const x=document.createElement('span');x.className='hero';x.textContent='🧑‍🎒';x.setAttribute('aria-hidden','true');b.appendChild(x)}if(st.wolf&&key(pos)===key(wolfPos())){const x=document.createElement('span');x.className='wolf';x.textContent='🐺';x.setAttribute('aria-hidden','true');b.appendChild(x)}gridEl.appendChild(b)}$('#words').innerHTML='';st.words.forEach(w=>{const b=document.createElement('button');b.className='wordbtn';if((w==='接近'&&state.stone)||(w==='通過'&&state.crossed)||(w==='到達'&&atExit()))b.classList.add('done');b.textContent=w;b.onclick=()=>showWord(w);$('#words').appendChild(b)});const wait=$('#waitBtn'),controls=$('.controls');wait.hidden=stageIndex!==5;wait.disabled=stageIndex!==5;controls.style.gridTemplateColumns=stageIndex===5?'1.25fr 1fr 1fr':'1fr 1fr';$('#inspectBtn').textContent=inspect?'이동으로':'살펴보기';$('#inspectBtn').className='control'+(inspect?' mode':'');$('#undoBtn').disabled=!history.length}
function tapCell(pos){if(inspect){showInspect(pos);return}if(!selected){if(key(pos)===key(state.hero)){selected=true;setStatus('좋아. 이제 옆 칸을 눌러 이동해.','info');render();return}setStatus('먼저 용사를 눌러줘.','info');return}if(key(pos)===key(state.hero)){setStatus('이동할 옆 칸을 골라봐.');return}if(dist(state.hero,pos)!==1){setStatus('한 번에 상하좌우 한 칸만 움직일 수 있어.','info');return}attemptMove(pos,false)}
function attemptMove(pos,isWait){const st=current(),ch=tileAt(pos);if(!isWait){if(!ch||ch==='#'||ch==='K'||(ch==='G'&&!state.stone)){setStatus(ch==='G'?'문이 아직 닫혀 있어.':'그쪽으로는 갈 수 없어.','info');return}if(ch==='X'){setStatus('這裡有危險。 가시를 피해 다른 길을 찾아봐.','bad');return}}const np=isWait?state.hero:pos;if(st.wolf){const cur=wolfPos(st,state),np2=st.wolf.cycle[nextPhase(st,state)];if(dist(np,cur)<=st.wolf.radius||dist(np,np2)<=st.wolf.radius){setStatus('太接近野狼了。 늑대와 거리를 더 두어야 해.','bad');return}}history.push(clone(state));const oldHero=clone(state.hero),oldTile=tileAt(oldHero);state.hero=clone(np);if(st.wolf)state.phase=nextPhase(st,state);state.turn++;const k=stonePos();if(k&&!state.stone&&dist(state.hero,k)===1){state.stone=true;setStatus('接近石碑 — 석비가 빛나며 길이 열렸어.','good')}if(st.ruin&&!isWait){const newTile=tileAt(state.hero),portals=st.ruin.portals;if(newTile==='R'&&oldTile!=='R'){const idx=portals.findIndex(p=>key(p)===key(oldHero));state.entry=idx>=0?idx:null}if(oldTile==='R'&&newTile!=='R'){const out=portals.findIndex(p=>key(p)===key(state.hero));if(state.entry!==null&&out>=0&&out!==state.entry){state.crossed=true;setStatus('已通過遺跡。 유적을 반대편까지 지나왔어.','good')}state.entry=null}}if(atExit()&&!isWin()){if(st.win.includes('crossed')&&!state.crossed)setStatus('還沒通過遺跡。 출구에는 왔지만 유적을 아직 통과하지 않았어.','info');else if(st.win.includes('stone')&&!state.stone)setStatus('아직 석비에 접근하지 않았어.','info')}if(isWin()){completed.add(st.id);save();render();setTimeout(showComplete,120);return}save();render();if(isWait)setStatus('한 턴 기다렸어. 늑대의 위치가 바뀌었어.','info')}
function showWord(w){const x=WORDS[w];openSheet(`<h2>${w}</h2><div class="pinyin">${x.p}</div><div class="meaning">${x.k}</div><div class="example">${x.ex}</div><div class="gamerule"><strong>이 판에서는</strong><br>${x.rule}</div><div class="sheetactions"><button onclick="closeSheet()">닫기</button></div>`)}
function showInspect(pos){const st=current(),ch=tileAt(pos),title=descTile(ch,pos);let extra='';if(st.wolf&&key(pos)===key(wolfPos())){const cur=wolfPos(),n=st.wolf.cycle[nextPhase()];extra=`<div class="gamerule">위험 범위: 현재와 다음 위치의 상하좌우 한 칸.<br>다음 행동: ${key(cur)===key(n)?'여기서 기다림':`${String.fromCharCode(65+n[1])}${n[0]+1}로 이동`}.</div>`}if(ch==='R'&&st.ruin)extra+='<div class="gamerule">연결된 유적 통로야. 한쪽 입구에서 들어가 다른 입구로 나오면 <b>通過</b>가 성립해.</div>';if(ch==='K')extra+='<div class="gamerule">위에 올라갈 수는 없어. 가까이 가면 반응할 것 같아.</div>';if(ch==='X')extra+='<div class="gamerule">위험한 가시야. 이 칸으로 들어가는 행동은 확정되지 않아.</div>';openSheet(`<h2>${title}</h2><div class="pinyin">${String.fromCharCode(65+pos[1])}${pos[0]+1}</div>${extra}<div class="sheetactions"><button onclick="closeSheet()">닫기</button></div>`)}
function openSheet(html){$('#sheet').innerHTML=html;$('#scrim').classList.add('open')}
window.closeSheet=()=>$('#scrim').classList.remove('open');
function showComplete(){const st=current(),last=stageIndex===STAGES.length-1;openSheet(`<div class="completeMark">${last?'🌄':'✓'}</div><h2 style="text-align:center">${last?'튜토리얼 완료':'스테이지 완료'}</h2><div class="story">${st.story}</div><div class="sheetactions">${stageIndex>0?'<button class="secondary" onclick="replayStage()">다시 해보기</button>':''}<button onclick="nextStage()">${last?'처음부터 보기':'다음 스테이지'}</button></div>`)}
window.nextStage=()=>{closeSheet();if(stageIndex<STAGES.length-1)stageIndex++;else stageIndex=0;resetStage()};window.replayStage=()=>{closeSheet();resetStage()};window.jumpStage=i=>{stageIndex=i;closeSheet();resetStage()};
function showMenu(){const list=STAGES.map((s,i)=>`<button class="stagepick" onclick="jumpStage(${i})"><strong>${completed.has(s.id)?'✓ ':''}${i}. ${s.title}</strong><small>${s.subtitle}</small></button>`).join('');openSheet(`<h2>出發</h2><div class="pinyin">튜토리얼 스테이지 선택</div><div class="menuList">${list}</div><div class="sheetactions"><button class="secondary" onclick="closeSheet()">닫기</button></div>`)}
$('#scrim').addEventListener('click',e=>{if(e.target.id==='scrim')closeSheet()});$('#menuBtn').onclick=showMenu;$('#resetBtn').onclick=()=>resetStage();$('#inspectBtn').onclick=()=>{inspect=!inspect;setStatus(inspect?'살펴보기 모드야. 지형이나 늑대를 눌러봐.':'이동 모드로 돌아왔어.','info');render()};$('#undoBtn').onclick=()=>{if(!history.length)return;state=history.pop();setStatus('직전 행동 전으로 되돌렸어.','info');save();render()};$('#waitBtn').onclick=()=>attemptMove(state.hero,true);
if(!load())resetStage(true);render();if(stageIndex===0&&!selected)setStatus('용사를 누르고, 화살표가 보이는 옆 칸을 눌러봐.','info');else if(stageIndex===5)setStatus('늑대는 행동할 때마다 움직여. 1턴 기다리기는 제자리에 머물며 늑대의 순찰만 진행시켜.','info');else setStatus('목표와 지형을 보고 네 길을 찾아봐.','info');